# Generated by Django 3.1.7 on 2021-03-25 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=300, null=True, verbose_name='Nombre_categoria')),
                ('descripcion', models.TextField(help_text='ingrese una descripcipón del animal', null=True, verbose_name='Descripcion animal')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gallo', models.CharField(max_length=200, null=True, verbose_name='Nombre_gallo')),
                ('slug', models.SlugField()),
                ('descripcion', models.TextField(help_text='ingrese una descripcipón del animal', null=True, verbose_name='Descripcion animal')),
                ('precio', models.IntegerField(null=True)),
                ('origen_animal', models.TextField(help_text='ingrese el origen del animal', null=True, verbose_name='origen_animal')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='portafolio/static/images', verbose_name='Foto_animal')),
                ('disponible', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
